
import { Article, Category } from './types';

export const ARTICLES: Article[] = [
  {
    id: '1',
    title: "Le Futur de la Carrosserie : Diagnostic par IA",
    slug: "futur-carrosserie-ia",
    excerpt: "Comment l'intelligence artificielle révolutionne l'estimation des dommages et les contrôles d'intégrité structurelle.",
    content: "L'industrie de la réparation après collision subit une transformation numérique sans précédent. Aujourd'hui, les outils de balayage assistés par IA peuvent détecter des micro-fractures invisibles à l'œil nu, garantissant une sécurité totale après une réparation. Ces technologies réduisent les délais d'attente pour les clients tout en augmentant la précision des devis envoyés aux assureurs. Les capteurs modernes et la vision par ordinateur sont désormais les outils primordiaux des techniciens de haut niveau.",
    category: Category.SAFETY,
    author: "Jean Dupont",
    publishDate: "2024-05-20",
    imageUrl: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=800&q=80",
    featured: true,
    tags: ["IA", "Technologie", "Sécurité"]
  },
  {
    id: '2',
    title: "5 Étapes pour Gérer votre Sinistre sans Stress",
    slug: "gerer-sinistre-assurance",
    excerpt: "Un guide pratique pour naviguer entre les experts, votre compagnie d'assurance et l'atelier de carrosserie.",
    content: "Après un accident, le niveau de stress est élevé. Cependant, suivre une procédure rigoureuse peut vous faire gagner du temps et de l'argent. Du rapport initial au dépôt de la plainte, voici comment maximiser vos chances d'une couverture complète. Comprendre vos droits concernant le libre choix du réparateur est vital dans le paysage actuel des assurances.",
    category: Category.INSURANCE,
    author: "Sarah Martin",
    publishDate: "2024-05-18",
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80",
    tags: ["Assurance", "Conseils", "Légal"]
  },
  {
    id: '3',
    title: "Réparation de Véhicules Électriques : Défis Spécifiques",
    slug: "reparation-vehicule-electrique",
    excerpt: "Pourquoi réparer une Tesla ou une ID.4 nécessite une formation haute tension et un équipement de sécurité spécifique.",
    content: "Une voiture électrique n'est pas comme un véhicule thermique traditionnel. Le circuit haute tension nécessite des protocoles de sécurité drastiques avant toute intervention sur la carrosserie. Découvrez pourquoi il est crucial de choisir un centre de réparation certifié qui comprend l'isolation des batteries et les systèmes de gestion thermique.",
    category: Category.REPAIR,
    author: "Michel Auto",
    publishDate: "2024-05-15",
    imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80",
    tags: ["EV", "Électrique", "Réparation"]
  },
  {
    id: '4',
    title: "Calibration ADAS : La Face Invisible de la Réparation Moderne",
    slug: "calibration-adas-securite",
    excerpt: "Les systèmes d'aide à la conduite doivent être recalibrés après presque tout travail de carrosserie.",
    content: "Les voitures modernes sont des ordinateurs sur roues. Après un accrochage mineur, vos capteurs de maintien de voie et de freinage d'urgence pourraient être désalignés. La calibration n'est plus optionnelle ; c'est une étape de sécurité critique qui nécessite un équipement spécialisé et des environnements contrôlés.",
    category: Category.SAFETY,
    author: "Robert Chen",
    publishDate: "2024-05-14",
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    tags: ["ADAS", "Tech", "Sécurité"]
  },
  {
    id: '5',
    title: "Peinture Éco-Responsable : Durabilité en Atelier",
    slug: "peinture-eco-responsable",
    excerpt: "Comment les peintures à l'eau réduisent l'empreinte carbone de l'industrie de la collision.",
    content: "Les réglementations environnementales stimulent l'innovation dans les finitions automobiles. Les systèmes de peinture hydrodiluables réduisent considérablement les émissions de composés organiques volatils (COV), offrant un environnement plus sûr pour les travailleurs et une empreinte réduite pour la planète, sans compromis sur la correspondance des couleurs ou la durabilité.",
    category: Category.INDUSTRY,
    author: "Elena Green",
    publishDate: "2024-05-12",
    imageUrl: "https://images.unsplash.com/photo-1590099433100-344c207a9747?auto=format&fit=crop&w=800&q=80",
    tags: ["Environnement", "Peinture", "Industrie"]
  },
  {
    id: '6',
    title: "L'Importance du Redressage de Châssis au Laser",
    slug: "redressage-chassis-laser",
    excerpt: "La précision millimétrique est requise pour restaurer la sécurité structurelle d'origine.",
    content: "Un châssis tordu peut rendre un véhicule imprévisible. Le système laser permet de mesurer les points d'ancrage avec une précision extrême, assurant que le véhicule se comporte exactement comme prévu lors d'un futur impact éventuel.",
    category: Category.REPAIR,
    author: "Marc Carrossier",
    publishDate: "2024-05-10",
    imageUrl: "https://images.unsplash.com/photo-1517524008697-84bef82b884e?auto=format&fit=crop&w=800&q=80",
    tags: ["Châssis", "Laser", "Structure"]
  },
  {
    id: '7',
    title: "Pièces OEM vs Adaptables : Le Grand Débat",
    slug: "oem-vs-aftermarket",
    excerpt: "Pourquoi le choix des pièces peut affecter la valeur de revente de votre voiture.",
    content: "Les pièces d'origine (OEM) garantissent un ajustement parfait. Les pièces adaptables sont moins chères mais peuvent parfois compromettre les zones de déformation programmées. Nous analysons les avantages de chaque option pour votre budget et votre sécurité.",
    category: Category.INSURANCE,
    author: "Pierre Expert",
    publishDate: "2024-05-09",
    imageUrl: "https://images.unsplash.com/photo-1506318137071-a8e063b4bcc0?auto=format&fit=crop&w=800&q=80",
    tags: ["Pièces", "Budget", "Expertise"]
  },
  {
    id: '8',
    title: "Comment Protéger votre Carrosserie contre la Corrosion",
    slug: "protection-corrosion-conseils",
    excerpt: "Les meilleures pratiques de maintenance pour éviter que la rouille ne détruise votre investissement.",
    content: "Le sel de déneigement et l'humidité sont les ennemis de l'acier. Un nettoyage régulier du soubassement et l'application de traitements anticorrosion peuvent prolonger la vie de votre carrosserie de plusieurs années.",
    category: Category.MAINTENANCE,
    author: "Lucie Brillance",
    publishDate: "2024-05-08",
    imageUrl: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80",
    tags: ["Entretien", "Rouille", "Hiver"]
  },
  {
    id: '9',
    title: "La Pénurie de Main-d'œuvre Qualifiée en Carrosserie",
    slug: "penurie-main-doeuvre-carrosserie",
    excerpt: "L'industrie fait face à un défi majeur pour recruter la prochaine génération de techniciens ADAS.",
    content: "Avec l'augmentation de la technologie embarquée, le métier de carrossier devient de plus en plus technique. Les centres de formation doivent s'adapter rapidement pour enseigner l'informatique autant que le travail du métal.",
    category: Category.INDUSTRY,
    author: "Antoine Boss",
    publishDate: "2024-05-07",
    imageUrl: "https://images.unsplash.com/photo-1530046339160-ce3e5b0c7a2f?auto=format&fit=crop&w=800&q=80",
    tags: ["Emploi", "Formation", "Industrie"]
  },
  {
    id: '10',
    title: "Réparation sans Peinture (DSP) : Les Avantages",
    slug: "dsp-debosselage-sans-peinture",
    excerpt: "Supprimer les bosses de grêle sans refaire la peinture complète : gain de temps et d'argent.",
    content: "Le débosselage sans peinture est un art. En utilisant des outils spécifiques pour repousser le métal par l'arrière, on conserve la peinture d'origine du constructeur, ce qui est idéal pour les véhicules haut de gamme.",
    category: Category.REPAIR,
    author: "Gérard Impact",
    publishDate: "2024-05-06",
    imageUrl: "https://images.unsplash.com/photo-1504222490345-c075b6008014?auto=format&fit=crop&w=800&q=80",
    tags: ["DSP", "Économie", "Technique"]
  },
  {
    id: '11',
    title: "Le Verre Automobile Intelligente",
    slug: "pare-brise-intelligent-adas",
    excerpt: "Pourquoi changer un pare-brise moderne coûte désormais plus de 1000 euros.",
    content: "Les pare-brise ne sont plus de simples vitres. Ils servent de support aux caméras ADAS. Après un remplacement, une recalibration logicielle est indispensable pour que le freinage d'urgence fonctionne.",
    category: Category.SAFETY,
    author: "Claire Vision",
    publishDate: "2024-05-05",
    imageUrl: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80",
    tags: ["Pare-brise", "Technologie", "Sécurité"]
  },
  {
    id: '12',
    title: "Assurance : Qu'est-ce que la Valeur de Remplacement ?",
    slug: "valeur-remplacement-assurance-auto",
    excerpt: "Comprendre les termes de votre contrat pour éviter les mauvaises surprises en cas de perte totale.",
    content: "Si votre véhicule est déclaré épave, l'assurance vous rembourse selon une valeur définie. VRADE, Valeur à Neuf ? Nous expliquons les nuances pour protéger votre patrimoine automobile.",
    category: Category.INSURANCE,
    author: "Franck Risk",
    publishDate: "2024-05-04",
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
    tags: ["Contrat", "Sinistre", "Argent"]
  },
  {
    id: '13',
    title: "L'Aluminium dans la Carrosserie : Un Défi pour les Ateliers",
    slug: "reparation-carrosserie-aluminium",
    excerpt: "L'aluminium ne se travaille pas comme l'acier. Il nécessite des postes de soudure dédiés.",
    content: "L'aluminium est plus léger mais possède une mémoire de forme différente. Les risques de corrosion galvanique imposent une séparation stricte des outils entre l'acier et l'aluminium en atelier.",
    category: Category.REPAIR,
    author: "Yann Métal",
    publishDate: "2024-05-03",
    imageUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=800&q=80",
    tags: ["Aluminium", "Soudure", "Technique"]
  },
  {
    id: '14',
    title: "Préparer sa Voiture pour la Revente : Le Detailing",
    slug: "detailing-revente-occasion",
    excerpt: "Investir 500€ dans une préparation esthétique peut vous rapporter 2000€ de plus à la revente.",
    content: "Un polissage complet, un nettoyage vapeur de l'habitacle et une protection cire font toute la différence pour un acheteur potentiel. L'aspect visuel est le premier levier de négociation.",
    category: Category.MAINTENANCE,
    author: "Karim Clean",
    publishDate: "2024-05-02",
    imageUrl: "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&w=800&q=80",
    tags: ["Vente", "Esthétique", "Conseils"]
  },
  {
    id: '15',
    title: "L'Impact des Scanners 3D sur l'Expertise Automobile",
    slug: "scanners-3d-expertise-collision",
    excerpt: "Les experts utilisent désormais la photogrammétrie pour documenter les accidents.",
    content: "La prise de vue 3D permet de recréer la scène de l'accident virtuellement. Cela facilite la détermination des responsabilités et la mesure précise de l'enfoncement structurel.",
    category: Category.INDUSTRY,
    author: "Julie Tech",
    publishDate: "2024-05-01",
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
    tags: ["3D", "Expertise", "Innovation"]
  },
  {
    id: '16',
    title: "Pourquoi les Phares LED sont si Chers à Remplacer ?",
    slug: "remplacement-phares-led-cout",
    excerpt: "Une optique moderne peut coûter le prix d'une petite voiture d'occasion.",
    content: "Les phares LED matriciels contiennent des processeurs et des ventilateurs. En cas de choc frontal léger, la facture peut s'envoler car ces blocs sont rarement réparables et doivent être remplacés en entier.",
    category: Category.REPAIR,
    author: "Simon Lumière",
    publishDate: "2024-04-30",
    imageUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    tags: ["LED", "Pièces", "Coût"]
  },
  {
    id: '17',
    title: "La Sécurité Passive : Airbags et Prétensionneurs",
    slug: "airbags-securite-passive-collision",
    excerpt: "Tout ce qui se passe en une fraction de seconde lors d'un déploiement d'airbag.",
    content: "Le système de retenue est complexe. Après un accident, il ne suffit pas de changer le coussin ; il faut remplacer les capteurs de choc et souvent le calculateur central pour garantir une protection future.",
    category: Category.SAFETY,
    author: "Paul Safety",
    publishDate: "2024-04-29",
    imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80",
    tags: ["Airbag", "Sécurité", "Crash"]
  },
  {
    id: '18',
    title: "Gérer un Sinistre à l'Étranger : Le Guide",
    slug: "sinistre-auto-etranger-guide",
    excerpt: "Que faire si vous avez un accident en vacances hors de votre pays ?",
    content: "Le constat européen simplifie les choses, mais les législations locales varient. Nous listons les numéros utiles et les réflexes à avoir pour que votre assistance fonctionne au mieux.",
    category: Category.INSURANCE,
    author: "Marie Voyage",
    publishDate: "2024-04-28",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    tags: ["Vacances", "Assurance", "International"]
  },
  {
    id: '19',
    title: "Nettoyage Moteur : Doit-on le Faire ?",
    slug: "nettoyage-moteur-avantages-risques",
    excerpt: "Un moteur propre est plus facile à inspecter, mais attention aux composants électroniques.",
    content: "Le lavage haute pression sur un moteur moderne est risqué. Utilisez plutôt des produits dégraissants spécifiques et protégez l'alternateur. Un moteur propre aide à détecter les fuites d'huile précocement.",
    category: Category.MAINTENANCE,
    author: "Thomas Méca",
    publishDate: "2024-04-27",
    imageUrl: "https://images.unsplash.com/photo-1486006396193-471a6f58bf6c?auto=format&fit=crop&w=800&q=80",
    tags: ["Moteur", "Entretien", "Mécanique"]
  },
  {
    id: '20',
    title: "L'Imprimante 3D arrive dans les Ateliers de Carrosserie",
    slug: "impression-3d-pieces-carrosserie",
    excerpt: "Fabriquer des petites pattes de fixation plutôt que de changer tout un pare-chocs.",
    content: "L'impression 3D permet de réparer des éléments plastiques coûteux. C'est une solution écologique qui évite le gaspillage et réduit les délais de livraison des pièces.",
    category: Category.INDUSTRY,
    author: "Fabien Créa",
    publishDate: "2024-04-26",
    imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=80",
    tags: ["3D", "Écologie", "Réparation"]
  },
  {
    id: '21',
    title: "Carrosserie Rapide : Le Concept en Plein Essor",
    slug: "carrosserie-rapide-concept",
    excerpt: "Réparer les petits bobos en moins de 24 heures pour satisfaire les clients pressés.",
    content: "Inspiré du 'Fast Food', la carrosserie rapide se concentre sur les rayures et petites bosses. Grâce à des processus optimisés, votre voiture ressort comme neuve en une journée seulement.",
    category: Category.REPAIR,
    author: "Vincent Speed",
    publishDate: "2024-04-25",
    imageUrl: "https://images.unsplash.com/photo-1507133311040-ae3ba94b2360?auto=format&fit=crop&w=800&q=80",
    tags: ["Rapidité", "Service", "Client"]
  },
  {
    id: '22',
    title: "Les Radars de Stationnement : Entretien et Panne",
    slug: "radars-stationnement-panne-carrosserie",
    excerpt: "Un simple voile de peinture trop épais peut rendre vos capteurs inopérants.",
    content: "Lors d'une peinture de pare-chocs, l'épaisseur du vernis sur les capteurs est cruciale. S'il y en a trop, le radar sonne en continu ou ne détecte plus rien. Une précision technique indispensable.",
    category: Category.SAFETY,
    author: "Alain bip",
    publishDate: "2024-04-24",
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    tags: ["Radar", "Électronique", "Peinture"]
  },
  {
    id: '23',
    title: "Le Malus Assurance après un Accident Responsable",
    slug: "malus-assurance-accident-responsable",
    excerpt: "Comment calculer l'impact d'un sinistre sur votre prime annuelle.",
    content: "Un accident responsable augmente votre coefficient de 25%. Nous calculons pour vous le temps nécessaire pour retrouver votre bonus initial et les alternatives pour changer d'assureur.",
    category: Category.INSURANCE,
    author: "Sophie Chiffre",
    publishDate: "2024-04-23",
    imageUrl: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=800&q=80",
    tags: ["Bonus", "Malus", "Argent"]
  },
  {
    id: '24',
    title: "Pneus et Parallélisme après un Choc Trottoir",
    slug: "parallelisme-pneus-apres-choc",
    excerpt: "Même si la jante n'a rien, la suspension a peut-être bougé.",
    content: "Un choc contre un trottoir peut fausser la géométrie. Cela entraîne une usure prématurée des pneus et une consommation accrue. Un contrôle de parallélisme est recommandé à chaque révision.",
    category: Category.MAINTENANCE,
    author: "Bruno Gomme",
    publishDate: "2024-04-22",
    imageUrl: "https://images.unsplash.com/photo-1544133782-b646fe8e6301?auto=format&fit=crop&w=800&q=80",
    tags: ["Pneus", "Géométrie", "Sécurité"]
  },
  {
    id: '25',
    title: "Le Marché de la Voiture d'Occasion Accidentée",
    slug: "marche-occasion-accidentee-vge",
    excerpt: "Acheter un véhicule VGE (Véhicule Gravement Endommagé) : opportunité ou danger ?",
    content: "Certains acheteurs se spécialisent dans le rachat de voitures accidentées pour les reconstruire. C'est légal sous strict contrôle d'expert, mais attention à l'historique lors de l'achat.",
    category: Category.INDUSTRY,
    author: "Éric Vente",
    publishDate: "2024-04-21",
    imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    tags: ["Occasion", "Expertise", "Business"]
  },
  {
    id: '26',
    title: "Soudure Plastique : Réparer plutôt que Jeter",
    slug: "soudure-plastique-pare-chocs",
    excerpt: "Comment les agrafes chauffantes permettent de sauver des pare-chocs fissurés.",
    content: "La réparation plastique est devenue ultra-performante. En soudant des agrafes en inox dans la structure du plastique, on retrouve une solidité équivalente au neuf, pour une fraction du prix.",
    category: Category.REPAIR,
    author: "Nicolas Fix",
    publishDate: "2024-04-20",
    imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=80",
    tags: ["Plastique", "Soudure", "Économie"]
  },
  {
    id: '27',
    title: "Vision de Nuit et Caméras Thermiques",
    slug: "vision-nuit-cameras-thermiques-auto",
    excerpt: "La prochaine frontière de la sécurité active arrive sur les modèles de série.",
    content: "Les caméras thermiques détectent les piétons bien avant que les phares ne les éclairent. Ces systèmes complexes demandent une calibration thermique précise en atelier spécialisé.",
    category: Category.SAFETY,
    author: "Hugo Nuit",
    publishDate: "2024-04-19",
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    tags: ["NightVision", "Sécurité", "Électronique"]
  },
  {
    id: '28',
    title: "Le Médiateur de l'Assurance : Votre Dernier Recours",
    slug: "mediateur-assurance-conflit-sinistre",
    excerpt: "En cas de désaccord avec votre expert, vous avez des recours gratuits.",
    content: "Si vous estimez que l'indemnisation proposée est insuffisante, le médiateur peut intervenir pour trouver une solution amiable avant d'aller au tribunal. Une procédure méconnue mais efficace.",
    category: Category.INSURANCE,
    author: "Jean Justice",
    publishDate: "2024-04-18",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80",
    tags: ["Justice", "Médiation", "Droit"]
  },
  {
    id: '29',
    title: "Nettoyage des Phares : Restaurer la Transparence",
    slug: "renovation-optiques-phares-ternes",
    excerpt: "Éviter le refus au contrôle technique à cause de phares opaques.",
    content: "Le polycarbonate des phares finit par jaunir. Un ponçage progressif suivi d'un vernissage UV redonne l'éclat du neuf et surtout toute la puissance d'éclairage nécessaire.",
    category: Category.MAINTENANCE,
    author: "Denis Brillance",
    publishDate: "2024-04-17",
    imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80",
    tags: ["Phares", "Rénovation", "Entretien"]
  },
  {
    id: '30',
    title: "L'Arrivée des Géants de la Tech dans l'Automobile",
    slug: "apple-google-auto-industrie-news",
    excerpt: "Apple et Google ne se contentent plus de CarPlay ; ils influencent la conception des voitures.",
    content: "L'interface homme-machine devient l'argument de vente numéro 1. Pour les carrossiers, cela signifie gérer des écrans géants et des connexions 5G complexes intégrés dans les planches de bord.",
    category: Category.INDUSTRY,
    author: "Marc Futur",
    publishDate: "2024-04-16",
    imageUrl: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80",
    tags: ["Tech", "Apple", "Google"]
  }
];
